export const PALETTE: Record<string, string> = {
  t: "transparent",
  k: "#111111", // outline
  w: "#FFFFFF",
  W: "#E0E0E0",
  g: "#385c2c",
  G: "#5ebd3e",
  y: "#f3d130",
  Y: "#b08f1b",
  r: "#e23838",
  R: "#973939",
  b: "#009cdf",
  B: "#005b9f",
  o: "#ea580c",
  O: "#c2410c",
  s: "#fca5a5", // skin
  S: "#f87171",
  c: "#00e5ff",
  C: "#008b99",
  x: "#9badb7",
  X: "#3f3f74",
  m: "#8b5c3e",
  M: "#5e3a24",
  P: "#83769c",
  p: "#ff77a8",
  l: "#3b82f6", // blue shirt
  L: "#1d4ed8", // dark blue
};

export type PixelFrame = string[];

export interface PixelCharacter {
  name: string;
  frames: PixelFrame[];
}

// Mapeo 24x24 de Perfil Lateral (Side-View) con secuencia de 4 frames
// Secuencia: 0 (Estirado), 1 (Arriba/Apoyo), 2 (Estirado invertido), 3 (Arriba/Apoyo invertido)

export const SPRITES_DATA: Record<string, PixelCharacter> = {

  // ==================== ISLA GAMING ====================
  master_chief: {
    name: "Master Chief",
    frames: [
      [ // F0: Stretch
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkggggkttttttttt",
        "ttttttttkggYYYgktttttttt",
        "ttttttttkkggYYgktttttttt",
        "ttttttttkGGggGkktttttttt",
        "ttttttttkkXGGXkttttttttt",
        "tttttttkXkXGgGktttkttttt",
        "tttttttkXkkGGXkttkXktttt",
        "tttttttkXgGXXkXkXkXktttt",
        "ttttttttkggGGgXkkXXbtttt",
        "tttttttkkgGggGkXXkkttttt",
        "ttttttkkXkgGGgkXkttttttt",
        "tttttkkXkttkGgkttttttttt",
        "tttttkkttttkggkttttttttt",
        "ttttXgkttttXggkttttttttt",
        "ttttggkttttkkXkttttttttt",
        "tttXggkttttttgXktttttttt",
        "tttkgXkttttttkggkttttttt",
        "tttkkXktttttttkkXktttttt",
        "ttttkktttttttttkkttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1: Up
        "tttttttttttttttttttttttt",
        "tttttttttkggggkttttttttt",
        "ttttttttkggYYYgktttttttt",
        "ttttttttkkggYYgktttttttt",
        "ttttttttkGGggGkktttttttt",
        "ttttttttkkXGGXkttttttttt",
        "tttttttkXkXGgGktttkttttt",
        "tttttttkXkkGGXkttkXktttt",
        "tttttttkXgGXXkXkXkXktttt",
        "ttttttttkggGGgXkkXXbtttt",
        "tttttttkkgGggGkXXkkttttt",
        "ttttttkkXkgGGgkXkttttttt",
        "ttttttkkkttkGgkttttttttt",
        "ttttttkXgkttggkttttttttt",
        "ttttttkgXkttXgkttttttttt",
        "ttttttttkXkttkggkttttttt",
        "ttttttttkggkttkXkttttttt",
        "tttttttttkkXkttkkttttttt",
        "ttttttttttkXkttttttttttt",
        "tttttttttttkkttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2: Stretch Inv
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkggggkttttttttt",
        "ttttttttkggYYYgktttttttt",
        "ttttttttkkggYYgktttttttt",
        "ttttttttkGGggGkktttttttt",
        "ttttttttkkXGGXkttttttttt",
        "tttttttkXkXGgGktttkttttt",
        "tttttttkXkkGGXkttkXktttt",
        "tttttttkXgGXXkXkXkXktttt",
        "ttttttttkggGGgXkkXXbtttt",
        "tttttttkkgGggGkXXkkttttt",
        "ttttttkkXkgGGgkXkttttttt",
        "ttttttkkkttkGgkttttttttt",
        "tttttXgkttttkggktttttttt",
        "ttttXggkttttkggktttttttt",
        "tttkgXktttttXgkttttttttt",
        "tttkkXktttttggXktttttttt",
        "ttttkkttttttkgXktttttttt",
        "ttttttttttttkXkktttttttt",
        "tttttttttttttkkttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3: Up Inv
        "tttttttttttttttttttttttt",
        "tttttttttkggggkttttttttt",
        "ttttttttkggYYYgktttttttt",
        "ttttttttkkggYYgktttttttt",
        "ttttttttkGGggGkktttttttt",
        "ttttttttkkXGGXkttttttttt",
        "tttttttkXkXGgGktttkttttt",
        "tttttttkXkkGGXkttkXktttt",
        "tttttttkXgGXXkXkXkXktttt",
        "ttttttttkggGGgXkkXXbtttt",
        "tttttttkkgGggGkXXkkttttt",
        "ttttttkkXkgGGgkXkttttttt",
        "ttttttkkkttkGgkttttttttt",
        "ttttttggkttkXgkttttttttt",
        "tttttXgktttkgXkttttttttt",
        "ttttkggkttttkXkttttttttt",
        "ttttXkttktttkkXktttttttt",
        "ttttkkttkkttttkXkttttttt",
        "ttttttttttkttttkkttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },
  grunt: {
    name: "Grunt Alien",
    frames: [
      [ // F0
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkkttttttttttttt",
        "ttttttttkOOktttttttttttt",
        "tttttttkOOOOkttttttttttt",
        "ttttttkkOOkOOktttttttttt",
        "tttttkkkkOkkOkkttttttttt",
        "tttttXkXXkkkkXkktttttttt",
        "ttttXkkXXkYYYkkkkkkttttt",
        "ttttXkXXkkYYYkYYkXkttttt",
        "ttttkXkkXkkYYkkckXXktttt",
        "tttttkkXkkkXXkkkkkXktttt",
        "ttttttkXXkgGXXkttkXktttt",
        "tttttttkXkgGkktttttttttt",
        "ttttttkkOkkOkktttttttttt",
        "tttttkXkOktkXXkttttttttt",
        "tttttkXXktttkkkttttttttt",
        "ttttkXXktttttkkttttttttt",
        "ttttkkkktttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkkttttttttttttt",
        "ttttttttkOOktttttttttttt",
        "tttttttkOOOOkttttttttttt",
        "ttttttkkOOkOOktttttttttt",
        "tttttkkkkOkkOkkttttttttt",
        "tttttXkXXkkkkXkktttttttt",
        "ttttXkkXXkYYYkkkkkkttttt",
        "ttttXkXXkkYYYkYYkXkttttt",
        "ttttkXkkXkkYYkkckXXktttt",
        "tttttkkXkkkXXkkkkkXktttt",
        "ttttttkXXkgGXXkttkXktttt",
        "tttttttkXkgGkktttttttttt",
        "ttttttkkOkkOkktttttttttt",
        "ttttttkXkkkkXkkttttttttt",
        "ttttttkXkttkXktttttttttt",
        "ttttttkkkttkXXkttttttttt",
        "ttttttttttttkkkttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkkttttttttttttt",
        "ttttttttkOOktttttttttttt",
        "tttttttkOOOOkttttttttttt",
        "ttttttkkOOkOOktttttttttt",
        "tttttkkkkOkkOkkttttttttt",
        "tttttXkXXkkkkXkktttttttt",
        "ttttXkkXXkYYYkkkkkkttttt",
        "ttttXkXXkkYYYkYYkXkttttt",
        "ttttkXkkXkkYYkkckXXktttt",
        "tttttkkXkkkXXkkkkkXktttt",
        "ttttttkXXkgGXXkttkXktttt",
        "tttttttkXkgGkktttttttttt",
        "ttttttkkOkkOkktttttttttt",
        "ttttttkXXkttkXkktttttttt",
        "tttttkkkXkttkXXktttttttt",
        "tttttkkttttttkXktttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkkttttttttttttt",
        "ttttttttkOOktttttttttttt",
        "tttttttkOOOOkttttttttttt",
        "ttttttkkOOkOOktttttttttt",
        "tttttkkkkOkkOkkttttttttt",
        "tttttXkXXkkkkXkktttttttt",
        "ttttXkkXXkYYYkkkkkkttttt",
        "ttttXkXXkkYYYkYYkXkttttt",
        "ttttkXkkXkkYYkkckXXktttt",
        "tttttkkXkkkXXkkkkkXktttt",
        "ttttttkXXkgGXXkttkXktttt",
        "tttttttkXkgGkktttttttttt",
        "ttttttkkOkkOkktttttttttt",
        "ttttttkXXkttkXkttttttttt",
        "tttttkkXkttttkXXkttttttt",
        "tttttkktttttkkkktttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },

  // ==================== ISLA CLÁSICA ====================
  explorer: {
    name: "Explorer",
    frames: [
      [ // F0
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkMMkkkoookkktttttttt",
        "ttttkMmMMkooooookttttttt",
        "ttttkMMMMkoooooktttttttt",
        "tttttkkMMkkooooktttttttt",
        "ttttttkkkttkookttttttttt",
        "tttttttxkttkoktttttttttt",
        "ttttttxxktttxktttttttttt",
        "tttttkkxktttxktttttttttt",
        "ttttkMmkttttxkkttttttttt",
        "ttttkMktttttkMmktttttttt",
        "ttttkktttttttkMktttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkMMkkkoookkktttttttt",
        "ttttkMmMMkooooookttttttt",
        "ttttkMMMMkoooooktttttttt",
        "tttttkkMMkkooooktttttttt",
        "ttttttkkkttkookttttttttt",
        "tttttttkkttxxktttttttttt",
        "ttttttxxkttkxxkttttttttt",
        "ttttttxkktttkxkttttttttt",
        "tttttkmMktttxkkttttttttt",
        "tttttkmkttttkMkttttttttt",
        "tttttkktttttkktttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkMMkkkoookkktttttttt",
        "ttttkMmMMkooooookttttttt",
        "ttttkMMMMkoooooktttttttt",
        "tttttkkMMkkooooktttttttt",
        "ttttttkkkttkookttttttttt",
        "tttttXxkttxxkttttttttttt",
        "ttttxxktttkxxktttttttttt",
        "ttttkxxkttkxxktttttttttt",
        "ttttkMmktttkMktttttttttt",
        "ttttkMktttttkktttttttttt",
        "ttttkktttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkMMkkkoookkktttttttt",
        "ttttkMmMMkooooookttttttt",
        "ttttkMMMMkoooooktttttttt",
        "tttttkkMMkkooooktttttttt",
        "ttttttkkkttkookttttttttt",
        "ttttttxktttxxktttttttttt",
        "tttttXXktttkxktttttttttt",
        "ttttxxkktttkmMkttttttttt",
        "ttttxkktttttkmkttttttttt",
        "ttkMmkttttttkktttttttttt",
        "ttkMkttttttttttttttttttt",
        "ttkktttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },
  fox: {
    name: "Woodland Fox",
    frames: [
      [ // F0: Estirado
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttkoOkktttttt",
        "tttttttttttkkoOOoOkktttt",
        "tttkkkkttttkooOkwkOOkttt",
        "ttkoOOOkkkkoooookooOOktt",
        "tkwwOOoOooOOOooookOOkttt",
        "tkwwwOkoOooooOoOkkkktttt",
        "ttkkkkkkkOkkOOkktttttttt",
        "tttttttkkOttkOtttttttttt",
        "ttttttkOOkttkOOktttttttt",
        "tttttkkkktttkkkttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1: Apoyo recogido
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttkoOkktttttt",
        "tttttktttttkkoOOoOkktttt",
        "ttttkoOkkkkooOkwkOOktttt",
        "tttwoOOOooOOooookooOOktt",
        "ttkwwwOooooOooookOOktttt",
        "tttkwwwkkkOoooOkkkkttttt",
        "ttttkkkttkOkkOkktttttttt",
        "ttttttttttkOttkOtttttttt",
        "tttttttttkOOkttkOOkttttt",
        "ttttttttkkkktttkkktttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2: Estirado Invertido
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttkoOkktttttt",
        "ttkkkttttttkkoOOoOkktttt",
        "tkoOOkkktttkooOkwkOOkttt",
        "tkwwOOOOooOOooookooOOktt",
        "tkwwooOooooooOookOOktttt",
        "ttkwwkkOkkkkOoOkkkkttttt",
        "ttttttkOOkttkOOkkttttttt",
        "ttttttkOOkttkOOktttttttt",
        "tttttkkkktttkkkttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3: Apoyo recogido
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttktttttttkoOkktttttt",
        "ttttkoOkkkttkoOOoOkktttt",
        "tttwoOOOooOOooOkwkOOkttt",
        "ttkwwwOoooooooookooOOktt",
        "tttkwwkoOooOooookOOktttt",
        "ttttkkkttkOoooOkkkkttttt",
        "tttttttttkOkkOkktttttttt",
        "tttttttttkOttkOttttttttt",
        "ttttttttkOOkttkOOktttttt",
        "tttttttkkkktttkkkttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },

  // ==================== ISLA PIZZA ====================
  chef: {
    name: "Pizza Chef",
    frames: [
      [ // F0
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttwwwwtttttttttt",
        "tttttttttwwwwwwttttttttt",
        "tttttttttwkkwkkwtttttttt",
        "tttttttttkkkkkkttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttksssksktttttttt",
        "tttkMMkttwwwwwkttttttttt",
        "ttkmMmMktwwwwwkttttttttt",
        "tttkMMkktwwrwwkttttttttt",
        "ttttkkktwwwrwwkttttttttt",
        "ttttttttwrrrrwkttttttttt",
        "ttttttttkrrrrktttttttttt",
        "ttttttttXXkttXXktttttttt",
        "tttttttXXktttXXktttttttt",
        "ttttttXXktttttXXkttttttt",
        "tttttXXktttttttXXktttttt",
        "tttttkktttttttttkktttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1
        "tttttttttttttttttttttttt",
        "ttttttttttwwwwtttttttttt",
        "tttttttttwwwwwwttttttttt",
        "tttttttttwkkwkkwtttttttt",
        "tttttttttkkkkkkttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttksssksktttttttt",
        "tttkMMkttwwwwwkttttttttt",
        "ttkmMmMktwwwwwkttttttttt",
        "tttkMMkktwwrwwkttttttttt",
        "ttttkkktwwwrwwkttttttttt",
        "ttttttttwrrrrwkttttttttt",
        "ttttttttkrrrrktttttttttt",
        "ttttttttXXkttXXktttttttt",
        "tttttttXXktttXXktttttttt",
        "ttttttXXktttttXXkttttttt",
        "ttttttkktttttttkkttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttwwwwtttttttttt",
        "tttttttttwwwwwwttttttttt",
        "tttttttttwkkwkkwtttttttt",
        "tttttttttkkkkkkttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttksssksktttttttt",
        "tttkMMkttwwwwwkttttttttt",
        "ttkmMmMktwwwwwkttttttttt",
        "tttkMMkktwwrwwkttttttttt",
        "ttttkkktwwwrwwkttttttttt",
        "ttttttttwrrrrwkttttttttt",
        "ttttttttkrrrrktttttttttt",
        "tttttttXXkttttXXkttttttt",
        "ttttttXXktttttXXkttttttt",
        "tttttXXktttttttXXktttttt",
        "tttttkktttttttttkktttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3
        "tttttttttttttttttttttttt",
        "ttttttttttwwwwtttttttttt",
        "tttttttttwwwwwwttttttttt",
        "tttttttttwkkwkkwtttttttt",
        "tttttttttkkkkkkttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttksssksktttttttt",
        "tttkMMkttwwwwwkttttttttt",
        "ttkmMmMktwwwwwkttttttttt",
        "tttkMMkktwwrwwkttttttttt",
        "ttttkkktwwwrwwkttttttttt",
        "ttttttttwrrrrwkttttttttt",
        "ttttttttkrrrrktttttttttt",
        "ttttttttXXkttXXktttttttt",
        "tttttttXXktttXXktttttttt",
        "ttttttXXktttttXXkttttttt",
        "ttttttkktttttttkkttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },
  pizza_slice: {
    name: "Living Pizza",
    frames: [
      [ // F0
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttkkkkttttttttt",
        "tttttttttkkOyykttttttttt",
        "tttttttttkOOOyyktttttttt",
        "ttttttttkOOoyyyktttttttt",
        "ttttttttkOOryyyykttttttt",
        "tttttttkoOoyyyyktttttttt",
        "tttttttkoOyyyyyWkttttttt",
        "ttttttkoOyyyyyWwkttttttt",
        "ttttttkoOyyyyyrrkttttttt",
        "tttttkoOoyyyyyyrkttttttt",
        "tttttkoOyykyyykkyktttttt",
        "ttttkoOyyyyyyyryyktttttt",
        "ttttkoOyyryykykyyktttttt",
        "tttkoOoyyyyyyyyyykkttttt",
        "tttkoOoyyyykyyykkktttttt",
        "tttkkOooooOkkkOOkttttttt",
        "tttttkkkkkkttrrktttttttt",
        "ttttttttttkttrrktttttttt",
        "ttttttttktttttkktttttttt",
        "tttttttkkttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttkkkktttttttttt",
        "ttttttttkkOyyktttttttttt",
        "ttttttttkOOOyykttttttttt",
        "tttttttkoooyyykttttttttt",
        "tttttttkoOryyyyktttttttt",
        "ttttttkoOoyyyykttttttttt",
        "ttttttkoOyyyyyWktttttttt",
        "tttttkoOyyyyyWwktttttttt",
        "tttttkoOyyyyyrrktttttttt",
        "ttttkoOoyyyyyyrktttttttt",
        "ttttkoOyykyyykkykttttttt",
        "tttkoOyyyyyyyryykttttttt",
        "tttkoOyyryykykyykttttttt",
        "ttkoOoyyyyyyyyyykktttttt",
        "ttkoOoyyyykyyykkkttttttt",
        "ttkkOooooOkkkOOktttttttt",
        "ttttkkkkkkttrrkttttttttt",
        "ttttttttttkkrrkttttttttt",
        "ttttttttttttkktttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttkkkkttttttttt",
        "tttttttttkkOyykttttttttt",
        "tttttttttkOOOyyktttttttt",
        "ttttttttkOOoyyyktttttttt",
        "ttttttttkOOryyyykttttttt",
        "tttttttkoOoyyyyktttttttt",
        "tttttttkoOyyyyyWkttttttt",
        "ttttttkoOyyyyyWwkttttttt",
        "ttttttkoOyyyyyrrkttttttt",
        "tttttkoOoyyyyyyrkttttttt",
        "tttttkoOyykyyykkyktttttt",
        "ttttkoOyyyyyyyryyktttttt",
        "ttttkoOyyryykykyyktttttt",
        "tttkoOoyyyyyyyyyykkttttt",
        "tttkoOoyyyykyyykkktttttt",
        "tttkkOooooOkkkOOkttttttt",
        "tttttkkkkkkttkkttttttttt",
        "ttttttttrrkttktttttttttt",
        "ttttttttrrktttkktttttttt",
        "ttttttttkktttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttkkkktttttttttt",
        "ttttttttkkOyyktttttttttt",
        "ttttttttkOOOyykttttttttt",
        "tttttttkoooyyykttttttttt",
        "tttttttkoOryyyyktttttttt",
        "ttttttkoOoyyyykttttttttt",
        "ttttttkoOyyyyyWktttttttt",
        "tttttkoOyyyyyWwktttttttt",
        "tttttkoOyyyyyrrktttttttt",
        "ttttkoOoyyyyyyrktttttttt",
        "ttttkoOyykyyykkykttttttt",
        "tttkoOyyyyyyyryykttttttt",
        "tttkoOyyryykykyykttttttt",
        "ttkoOoyyyyyyyyyykktttttt",
        "ttkoOoyyyykyyykkkttttttt",
        "ttkkOooooOkkkOOktttttttt",
        "ttttkkkkkkttrrkttttttttt",
        "tttttttttttkrrkttttttttt",
        "ttttttttttttkktttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },

  // ==================== ISLA ESTUDIO ====================
  hurried_student: {
    name: "Hurried Student",
    frames: [
      [ // F0
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkRRkkkllLkkktttttttt",
        "ttttkRrRRklllllLkttttttt",
        "ttttkRRRRkllllLktttttttt",
        "tttttkkRRkkllllktttttttt",
        "ttttttkkkttklLlktttttttt",
        "ttttttXXkttkXlkttttttttt",
        "tttttXXkttttkXXktttttttt",
        "ttttXXkttttttkXXkttttttt",
        "ttttXkttttttttXkkttttttt",
        "tttXXkttttttttkXXktttttt",
        "tttkkttttttttttkkttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkRRkkkllLkkktttttttt",
        "ttttkRrRRklllllLkttttttt",
        "ttttkRRRRkllllLktttttttt",
        "tttttkkRRkkllllktttttttt",
        "ttttttkkkttklLlktttttttt",
        "tttttttXXkttkXXktttttttt",
        "ttttttXXktttkXXktttttttt",
        "ttttttXkttttkXXktttttttt",
        "tttttXXkttttXXkttttttttt",
        "tttttkktttttkXkttttttttt",
        "ttttttttttttkktttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkRRkkkllLkkktttttttt",
        "ttttkRrRRklllllLkttttttt",
        "ttttkRRRRkllllLktttttttt",
        "tttttkkRRkkllllktttttttt",
        "ttttttkkkttklLlktttttttt",
        "tttttXXkttttkXXktttttttt",
        "ttttXXktttttkXXktttttttt",
        "tttXXkttttttkXkttttttttt",
        "tttXktttttttkXXktttttttt",
        "ttkkttttttttkXXktttttttt",
        "tttttttttttttkkttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3
        "tttttttttttttttttttttttt",
        "tttttttttkmmmkkttttttttt",
        "ttttttttkmmmmmmktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttkkktksssksktttttttt",
        "ttttkRRkkkllLkkktttttttt",
        "ttttkRrRRklllllLkttttttt",
        "ttttkRRRRkllllLktttttttt",
        "tttttkkRRkkllllktttttttt",
        "ttttttkkkttklLlktttttttt",
        "tttttttXXkttXXkttttttttt",
        "ttttttXXktttXXkttttttttt",
        "tttttXXkttttkXXktttttttt",
        "tttttXktttttXXkttttttttt",
        "ttttkkttttttkXkttttttttt",
        "ttttttttttttkktttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },
  coffee_scholar: {
    name: "Coffee Scholar",
    frames: [
      [ // F0
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkXXXkkttttttttt",
        "ttttttttkXXXXXXktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkMMMmMMkttwktttt",
        "tttttttkMmmMmmMkttWktttt",
        "tttttttkMMMMmMMkttWktttt",
        "ttttttttkMMMMMkkttWktttt",
        "tttttttttkkMkkttttkktttt",
        "tttttttttkXkttXXkttttttt",
        "ttttttttXXkttttkXXkttttt",
        "tttttttXXkttttttkXkttttt",
        "ttttttXXktttttttkXXktttt",
        "tttttXXkttttttttkXkktttt",
        "tttttkkttttttttttkkttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1
        "tttttttttttttttttttttttt",
        "tttttttttkXXXkkttttttttt",
        "ttttttttkXXXXXXktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkMMMmMMkttwktttt",
        "tttttttkMmmMmmMkttWktttt",
        "tttttttkMMMMmMMkttWktttt",
        "ttttttttkMMMMMkkttWktttt",
        "tttttttttkkMkkttttkktttt",
        "tttttttttkXXkttXXktttttt",
        "ttttttttXXktttkXXktttttt",
        "tttttttXXkttttkXkttttttt",
        "ttttttXXktttttXXkttttttt",
        "ttttttkkttttttkXkttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkXXXkkttttttttt",
        "ttttttttkXXXXXXktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkMMMmMMkttwktttt",
        "tttttttkMmmMmmMkttWktttt",
        "tttttttkMMMMmMMkttWktttt",
        "ttttttttkMMMMMkkttWktttt",
        "tttttttttkkMkkttttkktttt",
        "ttttttttXXkttttkXktttttt",
        "tttttttXXktttttkXXkttttt",
        "ttttttXXkttttttkXXkttttt",
        "tttttXXktttttttkXktttttt",
        "tttttkkttttttttkXXkttttt",
        "ttttttttttttttttkktttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3
        "tttttttttttttttttttttttt",
        "tttttttttkXXXkkttttttttt",
        "ttttttttkXXXXXXktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkskwsskttttttttt",
        "ttttttttkskskksktttttttt",
        "tttttttttkkssskttttttttt",
        "ttttttttkMMMmMMkttwktttt",
        "tttttttkMmmMmmMkttWktttt",
        "tttttttkMMMMmMMkttWktttt",
        "ttttttttkMMMMMkkttWktttt",
        "tttttttttkkMkkttttkktttt",
        "ttttttttXXktttkXXktttttt",
        "tttttttXXkttttkXXktttttt",
        "ttttttXXktttttkXXktttttt",
        "tttttXXkttttttXXkttttttt",
        "tttttkktttttttkXkttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },

  // ==================== ISLA CÓSMICA ====================
  astronaut: {
    name: "Zero-G Astronaut",
    frames: [
      [ // F0: Floating Forward
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkwwwkkttttttttt",
        "ttttttttkwwwYYYktttttttt",
        "ttttttttkwwYYYYktttttttt",
        "ttttttttkwwwYYwktttttttt",
        "tttttttttkkwwktttttttttt",
        "tttttkkkttwwwwkttttttttt",
        "ttttbXXkkkwwwwwktttttttt",
        "ttttbxXXkwWwwwWwkttttttt",
        "ttttbXXXkwwwwwWwkttttttt",
        "tttttkkXXkwwwwwktttttttt",
        "ttttttkkkttkwwkttttttttt",
        "tttttttwkttwwktttttttttt",
        "ttttttwwkttwwktttttttttt",
        "tttttwwktttwwktttttttttt",
        "tttttkkttttkkttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1: Floating Up
        "tttttttttttttttttttttttt",
        "tttttttttkwwwkkttttttttt",
        "ttttttttkwwwYYYktttttttt",
        "ttttttttkwwYYYYktttttttt",
        "ttttttttkwwwYYwktttttttt",
        "tttttttttkkwwktttttttttt",
        "tttttkkkttwwwwkttttttttt",
        "ttttbXXkkkwwwwwktttttttt",
        "ttttbxXXkwWwwwWwkttttttt",
        "ttttbXXXkwwwwwWwkttttttt",
        "tttttkkXXkwwwwwktttttttt",
        "ttttttkkkttkwwkttttttttt",
        "tttttttwktttwwkttttttttt",
        "ttttttwwktttwwkttttttttt",
        "ttttttkkttttkkwttttttttt",
        "tttttttttttttkkttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2: Floating Forward (Alternate Leg)
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttkwwwkkttttttttt",
        "ttttttttkwwwYYYktttttttt",
        "ttttttttkwwYYYYktttttttt",
        "ttttttttkwwwYYwktttttttt",
        "tttttttttkkwwktttttttttt",
        "tttttkkkttwwwwkttttttttt",
        "ttttbXXkkkwwwwwktttttttt",
        "ttttbxXXkwWwwwWwkttttttt",
        "ttttbXXXkwwwwwWwkttttttt",
        "tttttkkXXkwwwwwktttttttt",
        "ttttttkkkttkwwkttttttttt",
        "ttttttttwwkttwkttttttttt",
        "tttttttwwkttwwkttttttttt",
        "ttttttwwktttwwktttttttttt",
        "ttttttkkttttkktttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3: Floating Up (Alternate Leg)
        "tttttttttttttttttttttttt",
        "tttttttttkwwwkkttttttttt",
        "ttttttttkwwwYYYktttttttt",
        "ttttttttkwwYYYYktttttttt",
        "ttttttttkwwwYYwktttttttt",
        "tttttttttkkwwktttttttttt",
        "tttttkkkttwwwwkttttttttt",
        "ttttbXXkkkwwwwwktttttttt",
        "ttttbxXXkwWwwwWwkttttttt",
        "ttttbXXXkwwwwwWwkttttttt",
        "tttttkkXXkwwwwwktttttttt",
        "ttttttkkkttkwwkttttttttt",
        "ttttttttwwkttwkttttttttt",
        "tttttttwwktttwwktttttttt",
        "ttttttkkwttttkkwtttttttt",
        "tttttttkktttttkktttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  },
  mini_droid: {
    name: "Mini Scout Droid",
    frames: [
      [ // F0: Treads moving
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttkrrkttttttt",
        "tttttttttttttkrrkttttttt",
        "ttttttttttttttkktttttttt",
        "ttttttttttttttXktttttttt",
        "ttttttttttkkkkXkkttttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkwwwwwwwktttttt",
        "tttttttttkXXkXXkXktttttt",
        "ttttttttXXXXXXXXXXtttttt",
        "ttttttkkkXXkkkkXXkkktttt",
        "ttttttXXxXXxXXxXXxXXtttt",
        "ttttttXXXXXXXXXXXXXXtttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F1: Bob up
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttkrrkttttttt",
        "tttttttttttttkrrkttttttt",
        "ttttttttttttttkktttttttt",
        "ttttttttttttttXktttttttt",
        "ttttttttttkkkkXkkttttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkwwwwwwwktttttt",
        "tttttttttkXXkXXkXktttttt",
        "ttttttttXXXXXXXXXXtttttt",
        "ttttttkkkXXkkkkXXkkktttt",
        "ttttttXXxXXxXXxXXxXXtttt",
        "ttttttXXXXXXXXXXXXXXtttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F2: Treads moving
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttkrrkttttttt",
        "tttttttttttttkrrkttttttt",
        "ttttttttttttttkktttttttt",
        "ttttttttttttttXktttttttt",
        "ttttttttttkkkkXkkttttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkwwwwwwwktttttt",
        "tttttttttkXXkXXkXktttttt",
        "ttttttttXXXXXXXXXXtttttt",
        "ttttttkkkXXkkkkXXkkktttt",
        "ttttttXXxXXxXXxXXxXXtttt",
        "ttttttXXXXXXXXXXXXXXtttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ],
      [ // F3: Bob up
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "ttttttttttttttkktttttttt",
        "tttttttttttttkrrkttttttt",
        "tttttttttttttkrrkttttttt",
        "ttttttttttttttkktttttttt",
        "ttttttttttttttXktttttttt",
        "ttttttttttkkkkXkkttttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkwWWWwWwktttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkWwcccccwkttttt",
        "tttttttttkwwwwwwwktttttt",
        "tttttttttkXXkXXkXktttttt",
        "ttttttttXXXXXXXXXXtttttt",
        "ttttttkkkXXkkkkXXkkktttt",
        "ttttttXXxXXxXXxXXxXXtttt",
        "ttttttXXXXXXXXXXXXXXtttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt",
        "tttttttttttttttttttttttt"
      ]
    ]
  }
};
