import { PlantType } from "./useForest";

export const PLANT_TYPES: PlantType[] = [
  {
    "id": "maleza-vereda",
    "name": "Maleza de Vereda",
    "emoji": "🌱",
    "description": "Un yuyo rebelde pero humilde que brotó entre dos baldosas rotas de la facultad.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 20,
    "speedMultiplierDescription": "20 min (+5.0% / min)",
    "color": "#84CC16",
    "accentColor": "#4D7C0F",
    "lore": "No tiene flores ni aroma refinado, pero sobrevive a cualquier pisada de parcial."
  },
  {
    "id": "lata-aplastada",
    "name": "Lata Aplastada con Pastito",
    "emoji": "🥫",
    "description": "Una lata de refresco pisada en el pasto de la que asoma un tímido tallo verde.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 22,
    "speedMultiplierDescription": "22 min (+4.5% / min)",
    "color": "#64748B",
    "accentColor": "#22C55E",
    "lore": "El aluminio oxidado le da una sombra precaria pero suficiente para 20 minutos de lectura."
  },
  {
    "id": "arbusto-pelado",
    "name": "Matorral Despeinado",
    "emoji": "🌾",
    "description": "Un arbusto torcido, despeinado y flacucho que parece haber trasnochado toda la semana.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 25,
    "speedMultiplierDescription": "25 min (+4.0% / min)",
    "color": "#A3E635",
    "accentColor": "#713F12",
    "lore": "Tiene pocas hojas y muchas ramas chuecas, pero aguanta con dignidad tu primer pomodoro."
  },
  {
    "id": "papel-cupcake",
    "name": "Molde de Cupcake Usado",
    "emoji": "🧁",
    "description": "Un pirotín de papel arrugado con restos de dulce donde nació una pequeña margarita amarilla.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 20,
    "speedMultiplierDescription": "20 min (+5.0% / min)",
    "color": "#F472B6",
    "accentColor": "#FBBF24",
    "lore": "El azúcar pegado al papel alimenta a la flor más dulce de los descansos cortos."
  },
  {
    "id": "diente-leon",
    "name": "Diente de León Pelado",
    "emoji": "🥀",
    "description": "Un tallito solitario que ya perdió casi todas sus semillas de tanto que le soplaron.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 24,
    "speedMultiplierDescription": "24 min (+4.1% / min)",
    "color": "#FACC15",
    "accentColor": "#65A30D",
    "lore": "Le queda una sola plumita blanca. Si estudias 25 minutos, tal vez vuele a cumplir un deseo."
  },
  {
    "id": "cardo-espinoso",
    "name": "Cardo Solitario de Baldío",
    "emoji": "🌵",
    "description": "Una espina grisácea con un pompón morado desinflado. Te pincha si te distraes con TikTok.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 26,
    "speedMultiplierDescription": "26 min (+3.8% / min)",
    "color": "#94A3B8",
    "accentColor": "#A855F7",
    "lore": "Nadie lo riega en el terreno abandonado, por eso le alcanza con un sorbo de concentración."
  },
  {
    "id": "dpad-roto",
    "name": "D-Pad Roto de Family Game",
    "emoji": "🕹️",
    "description": "Una cruzeta de plástico gastado medio enterrada en la tierra con una brizna de pasto.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 25,
    "speedMultiplierDescription": "25 min (+4.0% / min)",
    "color": "#71717A",
    "accentColor": "#4ADE80",
    "lore": "Sobrevivió a mil partidas de la infancia; ahora vigila que no pierdas vidas en tu sesión."
  },
  {
    "id": "vaso-cafe",
    "name": "Vasito Descartable Tirado",
    "emoji": "☕",
    "description": "Un vasito blanco aplastado con una gota de café frío de máquina y un brote que asoma por la tapa.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 22,
    "speedMultiplierDescription": "22 min (+4.5% / min)",
    "color": "#E2E8F0",
    "accentColor": "#78350F",
    "lore": "El clásico fósil de buffet universitario reciclado por la naturaleza."
  },
  {
    "id": "fanzine-humedo",
    "name": "Fotocopia de Apunte Arrugada",
    "emoji": "📄",
    "description": "Un resumen fotocopiado doblado en cuatro con manchas de resaltador y una ramita seca.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 25,
    "speedMultiplierDescription": "25 min (+4.0% / min)",
    "color": "#FEF08A",
    "accentColor": "#0284C7",
    "lore": "Contiene fórmulas borrosas de la unidad 1 que nadie llegó a memorizar."
  },
  {
    "id": "pizza-fria",
    "name": "Porción Fría con Honguito",
    "emoji": "🍕",
    "description": "Un borde duro de pizza de anteayer sobre una servilleta grasosa donde creció un hongo gracioso.",
    "rarity": "comun",
    "level": 1,
    "levelLabel": "Muy Fácil",
    "difficulty": "muy_facil",
    "difficultyLabel": "Muy Fácil",
    "requiredMinutes": 28,
    "speedMultiplierDescription": "28 min (+3.5% / min)",
    "color": "#D97706",
    "accentColor": "#EF4444",
    "lore": "El desayuno no oficial de los estudiantes en semana de entregas finales."
  },
  {
    "id": "cactus-lata",
    "name": "Cactus en Lata de Conserva",
    "emoji": "🌵",
    "description": "Un cactus redondito y gordo plantado en una lata de arvejas reciclada con flor fucsia.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 45,
    "speedMultiplierDescription": "45 min (+2.2% / min)",
    "color": "#10B981",
    "accentColor": "#F43F5E",
    "lore": "No exige casi nada de agua, ideal para arrancar la tarde sin ahogarte en dudas."
  },
  {
    "id": "girasol-enano",
    "name": "Girasol Bebé Mareado",
    "emoji": "🌻",
    "description": "Girasol petiso de 30 cm que intenta seguir la luz de tu pantalla de computadora.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 50,
    "speedMultiplierDescription": "50 min (+2.0% / min)",
    "color": "#FACC15",
    "accentColor": "#713F12",
    "lore": "Tiene una carita sonriente en las semillas centrales que te anima en cada página."
  },
  {
    "id": "trebol-comun",
    "name": "Trébol Común de Tres Hojas",
    "emoji": "☘️",
    "description": "Un trébol fresco y verde de tres hojitas con gotas de rocío matutino.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 45,
    "speedMultiplierDescription": "45 min (+2.2% / min)",
    "color": "#22C55E",
    "accentColor": "#15803D",
    "lore": "No tiene cuatro hojas para ganar la lotería, pero te da la constancia para aprobar el práctico."
  },
  {
    "id": "arbusto-te",
    "name": "Arbustito de Manzanilla",
    "emoji": "🌼",
    "description": "Pequeño arbusto aromático repleto de florecitas blancas con centro amarillo que calman los nervios.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 55,
    "speedMultiplierDescription": "55 min (+1.8% / min)",
    "color": "#FDE047",
    "accentColor": "#16A34A",
    "lore": "Su aroma a infusión casera baja las palpitaciones antes de rendir oral."
  },
  {
    "id": "carnivorous-baby",
    "name": "Carnívora con Dientes de Leche",
    "emoji": "🪴",
    "description": "Una pequeña Venus atrapamoscas bebé que intenta cazar mosquitas de fruta en tu escritorio.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 50,
    "speedMultiplierDescription": "50 min (+2.0% / min)",
    "color": "#84CC16",
    "accentColor": "#DC2626",
    "lore": "Todavía no asusta a nadie, pero muerde suavemente las ganas de agarrar el celular."
  },
  {
    "id": "gameboy-pixel",
    "name": "Consola Portátil 8-Bits",
    "emoji": "🎮",
    "description": "Carcasa retro gris con pantalla verde de fósforo donde germina un sprite de arbolito pixelado.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 48,
    "speedMultiplierDescription": "48 min (+2.1% / min)",
    "color": "#64748B",
    "accentColor": "#84CC16",
    "lore": "Cada minuto de estudio suena como un 'BEEP' nostálgico de nivel superado."
  },
  {
    "id": "soda-can",
    "name": "Lata de Refresco Helada",
    "emoji": "🥤",
    "description": "Una lata de refresco gamer bien fría parada sobre un zócalo de césped con gotas de condensación.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 50,
    "speedMultiplierDescription": "50 min (+2.0% / min)",
    "color": "#06B6D4",
    "accentColor": "#0284C7",
    "lore": "El clásico 'CLIK-CHHH' al abrirla marca el inicio de una sesión productiva."
  },
  {
    "id": "cupcake-simple",
    "name": "Cupcake Casero de Vainilla",
    "emoji": "🧁",
    "description": "Un cupcake horneado con barquillo crocante, crema batida rosa pastel y una cereza confitada.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 45,
    "speedMultiplierDescription": "45 min (+2.2% / min)",
    "color": "#F472B6",
    "accentColor": "#EF4444",
    "lore": "El premio perfecto para completar la primera tanda de ejercicios de la guía."
  },
  {
    "id": "comic-strip",
    "name": "Tira Cómica de Periódico",
    "emoji": "📰",
    "description": "Tres viñetas en blanco y negro con tramas mecánicas y un chiste sobre llegar tarde a clase.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 60,
    "speedMultiplierDescription": "60 min (+1.6% / min)",
    "color": "#E2E8F0",
    "accentColor": "#18181B",
    "lore": "El papel huele a tinta fresca de prensa matutina y café con medialunas."
  },
  {
    "id": "bamboo-flaco",
    "name": "Cañita de Bambú Solitaria",
    "emoji": "🎋",
    "description": "Un tallo de bambú tierno y flexible que se mece con el viento sin quebrarse jamás.",
    "rarity": "comun",
    "level": 2,
    "levelLabel": "Fácil",
    "difficulty": "facil",
    "difficultyLabel": "Fácil",
    "requiredMinutes": 55,
    "speedMultiplierDescription": "55 min (+1.8% / min)",
    "color": "#4ADE80",
    "accentColor": "#16A34A",
    "lore": "Te enseña la paciencia oriental: sus raíces crecen bajo tierra antes de dispararse al cielo."
  },
  {
    "id": "oak",
    "name": "Roble Clásico Frondoso",
    "emoji": "🌳",
    "description": "Tronco leñoso macizo con copa abundante de hojas verdes y bellotas doradas.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 120,
    "speedMultiplierDescription": "2 horas (+0.83% / min)",
    "color": "#16A34A",
    "accentColor": "#78350F",
    "lore": "El clásico monumento de la disciplina académica que resiste cualquier tormenta de exámenes."
  },
  {
    "id": "apple",
    "name": "Manzano de Newton Cargado",
    "emoji": "🍎",
    "description": "Copa esférica repleta de manzanas rojas y una que cae para inspirar leyes de la física.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 140,
    "speedMultiplierDescription": "2.3 horas (+0.71% / min)",
    "color": "#EF4444",
    "accentColor": "#15803D",
    "lore": "Bajo su sombra nacieron los cálculos más brillantes de la historia universitaria."
  },
  {
    "id": "cherry",
    "name": "Cerezo Sakura Japonés",
    "emoji": "🌸",
    "description": "Tronco zen retorcido con nubes de flores rosadas y pétalos que flotan suavemente.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 130,
    "speedMultiplierDescription": "2.1 horas (+0.76% / min)",
    "color": "#F472B6",
    "accentColor": "#422006",
    "lore": "Simboliza la belleza efímera de cada hora bien aprovechada en tu carrera."
  },
  {
    "id": "bonsai",
    "name": "Bonsai Ancestral Podado",
    "emoji": "🪴",
    "description": "Árbol miniatura centenario modelado en maceta de cerámica con copas en nube de estilo japonés.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 150,
    "speedMultiplierDescription": "2.5 horas (+0.66% / min)",
    "color": "#22C55E",
    "accentColor": "#522504",
    "lore": "Exige calma mental y respiración profunda. No hay atajos para podar la ignorancia."
  },
  {
    "id": "coffee",
    "name": "Árbol de Café Barista",
    "emoji": "☕",
    "description": "Arbusto cafetero lleno de cerezas de café rojas con una taza humeante de espresso recién servida.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 160,
    "speedMultiplierDescription": "2.6 horas (+0.62% / min)",
    "color": "#78350F",
    "accentColor": "#D97706",
    "lore": "El fiel aliado de las trasnoches universitarias destilado en raíces de pura cafeína."
  },
  {
    "id": "willow",
    "name": "Sauce Llorón Zen",
    "emoji": "🌿",
    "description": "Cúpula esmeralda con largas ramas colgantes que caen como cortinas de tranquilidad.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 150,
    "speedMultiplierDescription": "2.5 horas (+0.66% / min)",
    "color": "#0D9488",
    "accentColor": "#14B8A6",
    "lore": "Su follaje amortigua el ruido exterior y crea una burbuja de silencio absoluto para leer."
  },
  {
    "id": "joystick-arcade",
    "name": "Mini Arcade Cabinet Retro",
    "emoji": "🎰",
    "description": "Gabinete vertical vintage con marquesina iluminada TABE, pantalla de navecitas y palanca roja.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 135,
    "speedMultiplierDescription": "2.2 horas (+0.74% / min)",
    "color": "#0284C7",
    "accentColor": "#FACC15",
    "lore": "Insert coin para concentrarte. Las vidas extras se consiguen repasando los errores."
  },
  {
    "id": "comic-pow",
    "name": "Viñeta de Acción POW!",
    "emoji": "💥",
    "description": "Bocadillo de impacto explosivo estilo Roy Lichtenstein con estrellas amarillas y trama de puntos.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 140,
    "speedMultiplierDescription": "2.3 horas (+0.71% / min)",
    "color": "#FFE600",
    "accentColor": "#EF4444",
    "lore": "¡Un golpe demoledor a la procrastinación en glorioso color cuatricromía!"
  },
  {
    "id": "pizza-slice",
    "name": "Árbol Pizza con Mozzarella",
    "emoji": "🍕",
    "description": "Corteza horneada crujiente con abundante queso derretido estirándose y rodajas de pepperoni.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 145,
    "speedMultiplierDescription": "2.4 horas (+0.69% / min)",
    "color": "#FACC15",
    "accentColor": "#DC2626",
    "lore": "El sabor inconfundible del festejo cuando logras resolver el ejercicio más largo de la guía."
  },
  {
    "id": "soda-cola",
    "name": "Botella de Cola Clásica",
    "emoji": "🍾",
    "description": "Botella de vidrio contorneada vintage con etiqueta roja de caligrafía, chapa metálica y gas efervescente.",
    "rarity": "raro",
    "level": 3,
    "levelLabel": "Normal",
    "difficulty": "normal",
    "difficultyLabel": "Normal",
    "requiredMinutes": 130,
    "speedMultiplierDescription": "2.1 horas (+0.76% / min)",
    "color": "#DC2626",
    "accentColor": "#18181B",
    "lore": "Una reliquia de diseño industrial que refresca las tardes más intensas de estudio."
  },
  {
    "id": "baobab",
    "name": "Gran Baobab Sagrado",
    "emoji": "🌳",
    "description": "Tronco colosal como una torre de fortaleza africana con ramas altas que rozan las nubes.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 240,
    "speedMultiplierDescription": "4 horas (+0.41% / min)",
    "color": "#854D0E",
    "accentColor": "#65A30D",
    "lore": "Almacena miles de litros de agua en su interior, igual que tu memoria guarda unidades enteras."
  },
  {
    "id": "cyber",
    "name": "Árbol Cyber Glitch",
    "emoji": "💾",
    "description": "Tronco oscuro recorrido por pistas de circuitos de neón cian y follaje de cubos de datos isométricos.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 280,
    "speedMultiplierDescription": "4.6 horas (+0.35% / min)",
    "color": "#7C3AED",
    "accentColor": "#00E5FF",
    "lore": "Procesa teoremas a velocidad de reloj cuántico sin riesgo de colapso de memoria RAM."
  },
  {
    "id": "joystick-fightstick",
    "name": "Arcade Fightstick Pro (KO x99)",
    "emoji": "🕹️",
    "description": "Consola pesada de torneos con palanca Sanwa roja, 6 botones convexos RGB y sello de combo legendario.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 300,
    "speedMultiplierDescription": "5 horas (+0.33% / min)",
    "color": "#27272A",
    "accentColor": "#DC2626",
    "lore": "Para meter un combo perfecto de 5 horas seguidas sin soltar los libros."
  },
  {
    "id": "pizza-hamburguesa",
    "name": "Hamburguesa Gamer Tower",
    "emoji": "🍔",
    "description": "Torre colosal de pan con sésamo tostado, doble carne a la parrilla, cheddar derretido y panceta crocante.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 270,
    "speedMultiplierDescription": "4.5 horas (+0.37% / min)",
    "color": "#D97706",
    "accentColor": "#451A03",
    "lore": "Un monumento calórico que recarga los carbohidratos cerebrales para rendir con todo."
  },
  {
    "id": "comic-manga",
    "name": "Panel Manga Shonen",
    "emoji": "💥",
    "description": "Líneas de velocidad radiales, trama de puntos shonen y aura de poder de protagonista de anime.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 320,
    "speedMultiplierDescription": "5.3 horas (+0.31% / min)",
    "color": "#18181B",
    "accentColor": "#FFE600",
    "lore": "¡Despierta tu arco de entrenamiento final y rompe los límites de tu promedio!"
  },
  {
    "id": "soda-energy",
    "name": "Torre de Energizantes Eléctricos",
    "emoji": "⚡",
    "description": "Doble lata de energizante neón con relámpagos crepitantes, voltímetro analógico y chispas de plasma.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 310,
    "speedMultiplierDescription": "5.1 horas (+0.32% / min)",
    "color": "#06B6D4",
    "accentColor": "#FACC15",
    "lore": "Descarga 200 voltios de lucidez en las neuronas cansadas de la tarde."
  },
  {
    "id": "cupcake-donut",
    "name": "Triple Torre de Donas Glaseadas",
    "emoji": "🍩",
    "description": "Tres donas gigantes apiladas en un tronco de barquillo con glaseado de fresa, chocolate y chispas de arcoíris.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 260,
    "speedMultiplierDescription": "4.3 horas (+0.38% / min)",
    "color": "#EC4899",
    "accentColor": "#78350F",
    "lore": "La gravedad sucumbe ante la perfección redonda de este monumento de repostería."
  },
  {
    "id": "cactus-titan",
    "name": "Gran Saguaro del Desierto",
    "emoji": "🌵",
    "description": "Colosal cactus de 5 brazos con gruesas espinas de defensa y coronado por flores blancas nocturnas.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 330,
    "speedMultiplierDescription": "5.5 horas (+0.30% / min)",
    "color": "#059669",
    "accentColor": "#EA580C",
    "lore": "El centinela imperturbable del desierto que no se inmuta ante exámenes sorpresa."
  },
  {
    "id": "cupcake-fresa",
    "name": "Montaña de Frutillas & Barquillo",
    "emoji": "🍓",
    "description": "Volcán dulce con crema chantilly montada, frutillas caramelizadas y barquillos de chocolate.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 290,
    "speedMultiplierDescription": "4.8 horas (+0.34% / min)",
    "color": "#FB7185",
    "accentColor": "#E11D48",
    "lore": "Su aroma a pastelería artesanal combate la fatiga mental de las demostraciones matemáticas."
  },
  {
    "id": "coffee-frappe",
    "name": "Frappuccino Barista con Caramelo",
    "emoji": "🥤",
    "description": "Vaso alto transparente con capas de café helado, leche cremosa, cúpula de crema y espirales de caramelo.",
    "rarity": "epico",
    "level": 4,
    "levelLabel": "Difícil",
    "difficulty": "dificil",
    "difficultyLabel": "Difícil",
    "requiredMinutes": 280,
    "speedMultiplierDescription": "4.6 horas (+0.35% / min)",
    "color": "#D97706",
    "accentColor": "#15803D",
    "lore": "La recompensa suprema con sorbete verde que premia una maratón de estudio."
  },
  {
    "id": "fire",
    "name": "Árbol Fénix Ígneo Renacido",
    "emoji": "🔥",
    "description": "Tronco de carbón volcánico con copa de fuego vivo que renace de sus cenizas con cada parcial aprobado.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 540,
    "speedMultiplierDescription": "9 horas (+0.18% / min)",
    "color": "#EA580C",
    "accentColor": "#FBBF24",
    "lore": "No importa cuán difícil sea la materia: el fuego del conocimiento nunca se apaga."
  },
  {
    "id": "crystal",
    "name": "Cristal Cósmico de Amatista",
    "emoji": "🔮",
    "description": "Tronco prismático de cuarzo violeta con racimos de gemas facetadas que refractan la luz estelar.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 500,
    "speedMultiplierDescription": "8.3 horas (+0.20% / min)",
    "color": "#C026D3",
    "accentColor": "#F0ABFC",
    "lore": "Canaliza las frecuencias electromagnéticas del universo para retener fórmulas complejas."
  },
  {
    "id": "tabe-libros",
    "name": "Torre de Códices y Libros TABE",
    "emoji": "📚",
    "description": "Espiral ascendente de tomos antiguos encuadernados en cuero con escaleras de biblioteca y runas doradas.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 600,
    "speedMultiplierDescription": "10 horas (+0.16% / min)",
    "color": "#1E3A8A",
    "accentColor": "#F59E0B",
    "lore": "Contiene las respuestas a todas las preguntas de examen jamás formuladas por un profesor."
  },
  {
    "id": "comic-villano",
    "name": "Cómic Archi-Villano Noir",
    "emoji": "🦹",
    "description": "Silueta siniestra con capa sombría, ojos magenta fulgurantes y rayos eléctricos morados en la noche.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 520,
    "speedMultiplierDescription": "8.6 horas (+0.19% / min)",
    "color": "#3B0764",
    "accentColor": "#F43F5E",
    "lore": "El némesis que desafía a los héroes de la facultad a superar sus límites de resistencia."
  },
  {
    "id": "coffee-moka",
    "name": "Gran Cafetera Moka Italiana",
    "emoji": "☕",
    "description": "Monumento de aluminio pulido de 8 lados que silba densas nubes de vapor aromático y granos tostados.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 480,
    "speedMultiplierDescription": "8 horas (+0.20% / min)",
    "color": "#78350F",
    "accentColor": "#CBD5E1",
    "lore": "El rito sagrado del fuego lento que alimenta la mente de los investigadores más dedicados."
  },
  {
    "id": "carnivorous-giant",
    "name": "Planta Atrapa-Distracciones Gigante",
    "emoji": "🪴",
    "description": "Fauces colosales con espinas afiladas y néctar dulce que devora de un bocado las ganas de procrastinar.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 560,
    "speedMultiplierDescription": "9.3 horas (+0.17% / min)",
    "color": "#65A30D",
    "accentColor": "#BE185D",
    "lore": "Ningún teléfono celular ni pestaña de redes sociales se le escapa a sus colmillos verdes."
  },
  {
    "id": "soda-galaxica",
    "name": "Cóctel Galáctico de Nebulosa",
    "emoji": "🌌",
    "description": "Matraz esférico de cristal con licor estelar púrpura y cian con estrellas flotando en suspensión.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 510,
    "speedMultiplierDescription": "8.5 horas (+0.19% / min)",
    "color": "#3B0764",
    "accentColor": "#00E5FF",
    "lore": "Bebido por astronautas académicos antes de emprender viajes de investigación a lo desconocido."
  },
  {
    "id": "comic-superheroe",
    "name": "Emblema del Héroe Académico",
    "emoji": "🦸",
    "description": "Escudo dorado con alas de halcón y capa roja majestuosa que ondea desafiando a la tormenta de entregas.",
    "rarity": "epico",
    "level": 5,
    "levelLabel": "Épico",
    "difficulty": "epico",
    "difficultyLabel": "Épico",
    "requiredMinutes": 580,
    "speedMultiplierDescription": "9.6 horas (+0.17% / min)",
    "color": "#DC2626",
    "accentColor": "#FACC15",
    "lore": "No todos los héroes llevan capa: algunos llevan calculadora, apuntes y 8 horas de concentración."
  },
  {
    "id": "tabe-legend",
    "name": "🦉 Búho TABE Divino",
    "emoji": "🦉",
    "description": "¡TITÁN ANIMADO! Aletea sus alas doradas, parpadea con lentes estelares y levita el códice sagrado TABE.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 1200,
    "speedMultiplierDescription": "20 horas (+0.083% / min)",
    "color": "#BFFF00",
    "accentColor": "#FFE600",
    "lore": "El dios guardián supremo de TABE. Solo los estudiantes más perseverantes de la historia lo ven danzar."
  },
  {
    "id": "tabe-graduacion",
    "name": "🎓 Búho Doctorado Honoris Causa",
    "emoji": "🎓",
    "description": "¡TITÁN ANIMADO! Gira su birrete doctoral con borla áurea, viste toga de terciopelo y sostiene el diploma.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 1080,
    "speedMultiplierDescription": "18 horas (+0.092% / min)",
    "color": "#1E1B4B",
    "accentColor": "#F59E0B",
    "lore": "El símbolo cumbre de la graduación soñada tras años de entrega y pasión por aprender."
  },
  {
    "id": "joystick-god",
    "name": "👑 Trono Gaming Cuántico Divino",
    "emoji": "👑",
    "description": "¡TITÁN ANIMADO! Baila con ritmo cósmico, emite rayos láser y proyecta pantallas esféricas de energía oscura.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 1000,
    "speedMultiplierDescription": "16.6 horas (+0.1% / min)",
    "color": "#7C3AED",
    "accentColor": "#00E5FF",
    "lore": "La cúspide tecnológica reservada para quienes superan las 16 horas de estudio de élite."
  },
  {
    "id": "pizza-buffet",
    "name": "🍕 Buffet Legendario Sin Límites",
    "emoji": "🍕",
    "description": "¡TITÁN ANIMADO! La mesa imperial baila de alegría con pizza suprema, hamburguesas triples y papas crocantes.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 840,
    "speedMultiplierDescription": "14 horas (+0.119% / min)",
    "color": "#DC2626",
    "accentColor": "#FACC15",
    "lore": "El banquete celestial interminable para celebrar el fin de año con notas sobresalientes."
  },
  {
    "id": "cupcake-palace",
    "name": "🏰 Palacio de Azúcar & Diamantes",
    "emoji": "💎",
    "description": "¡TITÁN ANIMADO! Castillo de confitería que baila con música dulce, torres de barquillo y cereza de diamante.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 880,
    "speedMultiplierDescription": "14.6 horas (+0.113% / min)",
    "color": "#EC4899",
    "accentColor": "#A855F7",
    "lore": "La maravilla dulce reservada para los expedientes académicos más brillantes de la historia."
  },
  {
    "id": "coffee-infinity",
    "name": "♾️ Café Infinito de los Dioses",
    "emoji": "♾️",
    "description": "¡TITÁN ANIMADO! Cáliz de obsidiana que levita y juega con el vórtice de café dorado que nunca se vacía.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 950,
    "speedMultiplierDescription": "15.8 horas (+0.105% / min)",
    "color": "#451A03",
    "accentColor": "#F59E0B",
    "lore": "Bebido por los sabios de la antigüedad para desentrañar las leyes ocultas del cosmos."
  },
  {
    "id": "soda-hyperdrive",
    "name": "🚀 Reactor Líquido Hyperdrive",
    "emoji": "🚀",
    "description": "¡TITÁN ANIMADO! Reactor criogénico que flota expulsando chorros de plasma lumínico de hipervelocidad.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 900,
    "speedMultiplierDescription": "15 horas (+0.111% / min)",
    "color": "#00E5FF",
    "accentColor": "#3B82F6",
    "lore": "Rompe la barrera del tiempo para resolver semestres enteros con velocidad hiperespacial."
  },
  {
    "id": "golden",
    "name": "🪙 Árbol de Oro Imperial",
    "emoji": "🪙",
    "description": "¡TITÁN ANIMADO! Tronco de oro macizo de 24 kilates que pulsa con luz celestial y lluvia de monedas tintineantes.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 1000,
    "speedMultiplierDescription": "16.6 horas (+0.1% / min)",
    "color": "#FACC15",
    "accentColor": "#A16207",
    "lore": "Un monumento a la constancia inquebrantable de los mejores graduados con medalla de oro."
  },
  {
    "id": "rainbow",
    "name": "🌈 Árbol Prisma Arcoíris",
    "emoji": "🌈",
    "description": "¡TITÁN ANIMADO! 7 arcos espectrales que flotan y refractan destellos prismáticos vivos de pura energía.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 1080,
    "speedMultiplierDescription": "18 horas (+0.092% / min)",
    "color": "#38BDF8",
    "accentColor": "#F43F5E",
    "lore": "Reúne todas las frecuencias de la concentración en una sola obra de arte natural viviente."
  },
  {
    "id": "yggdrasil",
    "name": "🌌 Yggdrasil Árbol del Mundo",
    "emoji": "🌌",
    "description": "¡TITÁN ANIMADO! El árbol cósmico sagrado cuyas ramas respiran con una poderosa aura dimensional infinita.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 1200,
    "speedMultiplierDescription": "20 horas (+0.083% / min)",
    "color": "#6366F1",
    "accentColor": "#312E81",
    "lore": "En sus ramas descansan todos los saberes descubiertos por la humanidad a lo largo de los siglos."
  },
  {
    "id": "celestial",
    "name": "🌠 Sauce Celestial de Estrellas",
    "emoji": "🌠",
    "description": "¡TITÁN ANIMADO! Sauce transparente con constelaciones de estrellas que titilan y luna creciente resplandeciente.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 1140,
    "speedMultiplierDescription": "19 horas (+0.087% / min)",
    "color": "#38BDF8",
    "accentColor": "#0284C7",
    "lore": "Refleja el brillo inextinguible de la mente que nunca deja de tener curiosidad."
  },
  {
    "id": "comic-creator",
    "name": "✒️ Pluma de Autor Maestro Manga",
    "emoji": "✒️",
    "description": "¡TITÁN ANIMADO! Gran pluma G-Pen que se agita en combate creativo con tintero de nebulosa y viñetas flotantes.",
    "rarity": "legendario",
    "level": 6,
    "levelLabel": "Legendario",
    "difficulty": "legendario",
    "difficultyLabel": "Legendario",
    "requiredMinutes": 960,
    "speedMultiplierDescription": "16 horas (+0.104% / min)",
    "color": "#18181B",
    "accentColor": "#FFE600",
    "lore": "Quien posee esta pluma escribe su propio destino en el cuadro de honor de la universidad."
  }
];
